# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

orbs:
  win: circleci/windows@2.4.0


jobs:
  test:
    working_directory: ~/pyigtlink
    executor: win/default # executor type
    steps:
      - checkout
      - store_test_results
      - run:
          command: |
            pip install numpy crcmod
      - run: python pyIGTLink/tests.py
workflows:
  # Name the workflow "welcome"
  main:
    # Run the welcome/run job in its own container
    jobs:
      - test
